# Changes here will be overwritten by Copier
_commit: v2.0.2
_src_path: gh:lincc-frameworks/python-project-template
author_email: eeh55@cam.ac.uk
author_name: Erin E. Hayes
custom_install: false
package_name: gaussn
project_license: MIT
project_name: gaussn
project_organization: erinhay
